### ISSUE TITLE
Running from packaged electron app is unsupported

### ISSUE THREAD

**Issue by Methrat0n** [leinelissen/embedded-postgres#8] opened 2023-08-31 09:44 UTC
Hello,

We love the work done here, but it cannot work when run from an electron process.
I've found a workaround for now, but it's pretty manual and I'd like to fix it in your library so we can actually build with our CI.

Here are the changes I've made in my fork so it can work, please have a look : https://github.com/Methrat0n/embedded-postgres/pull/1

Would you be open to merge this in here ?
Also, can you help us test that more thoroughly, we're not sure how to install and build.

`npm i` does not seams to work 
`npm ERR! notsup Unsupported platform for @embedded-postgres/darwin-arm64@15.4.0-beta.9: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})`

And when doing npm run install for lerna to take over it does not seams to finish.
Whar are we missing please ?

**Comment by leinelissen** [comment] 2024-02-11 20:44
Hey @Methrat0n, sorry for not getting back to you. I am open to having this merged. Do you perhaps have a testing repository so I can verify the code is working as intended?

**Closed** 2024-10-28 07:13 UTC
